title:              More Than Dead, White Men?
email:              ingram.noel@gmail.com
description:        A Digital Humanities Project by Noël Ingram
author:             Noël Ingram
baseurl:            "/morethandeadwhitemen"
url:                "https://neingram.github.io/morethandeadwhitemen/"

# Social Profiles
twitter_username:   neingramm
github_username:    neingram
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
